# Permalinks
permalink:        pretty

# Setup
title:            Data Engineering Cookbook
tagline:          Recipes for Data Engineers
url:              http://www.helmutzechmann.com
paginate:         3
baseurl:          /
author:
  name:           Helmut Zechmann
  url:            https://twitter.com/hzechmann
  email:          markdotto@gmail.com


markdown: kramdown

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole


pages_list:       
  About: '/about'
  Cookbook: '/cookbook'
  Feed: '/atom.xml'