# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Data Engineering Cookbook
tagline:          The Jekyll Butler
url:              http://getpoole.com
paginate:         2
baseurl:          /
author:
  name:           Helmut Zechmann
  url:            https://twitter.com/hzechmann
  email:          markdotto@gmail.com


markdown: redcarpet

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole


pages_list:       
  About: '/about'
  Cookbook: '/cookbook'
  Feed: '/atom.xml'